config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :number_of_guests, presence: true
  validates :price_per_night, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def edit; end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flats_path, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @flat.destroy
    redirect_to restaurants_url, notice: 'Flat was successfully destroyed.'
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :price_per_night, :number_of_guests, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats (
        <%= Flat.count %>)</h1>
    </div>
  </div>

  <div class="row">
    <% @flats.each do |flat| %>

    <div class="col-4 mb-3">

      <div class="card one-edge-shadow" style="width: 18rem;">
        <div class="card-body bg-light">
          <h5 class="card-title">
            <%= flat.name %>
          </h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= flat.address %></h6>
          <i class="fas fa-user-friends"> <%= flat.number_of_guests %></i>
          <i class="fas fa-euro-sign"> <%= flat.price_per_night %></i>
          <div>
            <%= link_to "More info", flat_path(flat) %>
          </div>

        </div>
      </div>

    </div>

  <% end %>
    </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "mb-3 btn btn-primary"%>
    <% end %>
  </div>
  <%= link_to 'Back', flats_path, class: "btn btn-light" %>
</div>

app/views/flats/show.html.erb
<div class="map" style="background-image: url('/assets/map.png')"></div>
<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1>
          <%= @flat.name %>
        </h1>
        <p class="flat-show-address">
          <%= @flat.address %>
        </p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p>
          <%= @flat.description %>
        </p>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.4093428311203!2d-0.18527028422942!3d51.524051479637826!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761aa8b8a56fab%3A0x81d846cf9d085828!2s10%20Clifton%20Gardens%2C%20Little%20Venice%2C%20London%20W9%201DT%2C%20Regno%20Unito!5e0!3m2!1sit!2sde!4v1613576027355!5m2!1sit!2sde" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <i class="fas fa-user-friends">
          <%= @flat.number_of_guests %></i>
        <i class="fas fa-euro-sign">
          <%= @flat.price_per_night %></i>
      </div>
    </div>
    <div class="col-4">
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsSimpleAirbnb</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-light bg-light">
    <%= link_to 'Simple AirBnb', flats_path, class: "navbar-brand mb-0 h1" %>
    <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary" %>
  </nav>
  <%= yield %>
</body>

</html>